# 1. Workflow 이름 지정
name: CI

# 2. Workflow가 시작될 조건 지정
on:
  push:
    branches: ["main", "dev", "seonguk"]
  pull_request:
    branches: ["main", "dev"]


jobs:
  build:
    runs-on: ubuntu-latest # 3. 실행 환경 지정
    # 4. 실행 스텝 지정
    steps:
      - uses: actions/checkout@v3 # uses <- 지정한 리포지터리를 확인하고 코드에 대한 작업 실행

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew # name <- 스텝의 이름
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build