# 1. Workflow 이름 지정
name: CI

# 2. Workflow가 시작될 조건 지정
on:
  push:
    branches: [main, dev, seonguk]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경 지정
    services:
      redis: # Redis 서비스 추가
        image: redis:latest
        ports:
          - 6379:6379
        options: --requirepass "password123" # 필요시 Redis 인증 설정

    # 4. 실행 스텝 지정
    steps:
      - uses: actions/checkout@v3 # 코드 체크아웃

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Set environment variables # 환경 변수 설정
        run: |
          echo "REDIS_HOST=localhost" >> $GITHUB_ENV
          echo "REDIS_PORT=6379" >> $GITHUB_ENV
          echo "REDIS_PASSWORD=password123" >> $GITHUB_ENV # 필요시 추가

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test --info
